version: '3.7'
services: 

  frontend:
    container_name: frontend
    build: ./frontend
    ports: 
    - "80:8080"
    - "443:443"
    volumes:
    - ./frontend:/app
    stdin_open: true
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    
      

networks:
  backend:
    driver: bridge